### PR TITLE
fix: improve batcher verification error logging

### LINKED ISSUE #18731: Proof verification errors are suppressed and replaced with misleading messages
## Summary
Errors from proof verification are being suppressed. Instead of propagating the actual verification failure, the system replaces it with a misleading `Invalid_proof "In progress"` message.

## Observed behavior
- When proof verification fails:
  - the actual error is lost
  - the system reports:
    ```
    Invalid_proof "In progress"
    ```
- This is misleading and makes debugging much harder

## Root cause
In `verify_commands`:

```ocaml
let%map all_verified =
  Pickles.Side_loaded.verify ~typ:Zkapp_statement.typ to_verify
```

Then later:

```ocaml
| Ok (`Assuming xs) ->
    if Or_error.is_ok all_verified then `Valid else `Valid_assuming xs
```

If `all_verified` is an error:
- the error is ignored
- the result is downgraded to `Valid_assuming xs`

Downstream, batcher treats that as partial validity and eventually emits the misleading `Invalid_proof "In progress"` error.

## Why this is problematic
- Suppresses the only useful debugging signal
- Reports true proof failures as “proof still in progress” in log messages
- Causes misleading diagnostics

## Expected behavior
- Proof verification failures should preserve and surface the actual error
- Logs should distinguish genuine invalid proof failures from in-progress state

## Proposed fix
Preserve the verifier error in the return value, for example by changing the representation from:

```ocaml
`Valid_assuming xs
```

to something like:

```ocaml
`Valid_assuming (xs, error)
```

or another structured form that propagates the underlying `Or_error.t` through the batcher.

And then in the following code use the error message instaed of `In progress`:

```ocaml
| `In_progress a -> (
                  (* If the diff is all valid, we're done. If not, we return a partial
                       result. *)
                  match all_valid a with
                  | Some res ->
                      `Valid res
                  | None ->
                      `Potentially_invalid
                        ( list_of_array_map a ~f:(function
                            | `Unknown ->
                                assert false
                            | `Valid c ->
                                `Valid c
                            | `Valid_assuming (v, xs) ->
                                `Valid_assuming (v, xs) )
                        , Error.of_string "In progress" ) ) ) ) )
```

## Follow-up
Once this is fixed, rerun the failing max-cost transaction case to expose the real underlying proof failure.

### PR DESCRIPTION
**Pull request by glyh**
Should fix https://github.com/MinaProtocol/mina/issues/18731.

## Summary

This PR improves error reporting in the transaction pool batcher's verification pipeline. Previously, verification failures in the `Valid_assuming` path silently dropped the underlying error, making it impossible to diagnose why a batch of transactions was rejected. The error is now threaded through the entire pipeline and collected when a diff is marked as `Potentially_invalid`.

### `src/lib/verifier/common.ml`
- `check_signed_command` now filters and returns only the invalid public keys individually, rather than checking all keys at once via `check_valid_keys`.
- Switched from `check_only_for_signature` to `check_signature` for cleaner signature validation.

### `src/lib/verifier/verifier_intf.ml`, `dummy.ml`, `prod.ml`
- Extended the `` `Valid_assuming `` variant to carry an `Error.t` alongside the list of assumptions.
- The actual error from batch verification is now attached instead of being discarded.

### `src/lib/network_pool/batcher.ml`
- Updated all match arms on `` `Valid_assuming `` to handle the new `Error.t` field.
- When building a `Potentially_invalid` result, errors from all `` `Valid_assuming `` entries are collected and combined via `Error.of_list`. Falls back to a placeholder string when no errors were collected (guards against `Error.of_list` raising on an empty list).
- Minor cleanup: use `Array.create` instead of `Array.of_list_map` for initializing unknown-status arrays.

## Testing

No new tests — this is an error propagation fix. Existing tests cover the verification paths.

### CODE REVIEW

File: src/lib/network_pool/batcher.ml [hunk 1]
```diff
@@ -402,15 +403,31 @@ module Transaction_pool = struct
...
+                             | _ ->
+                                 None )
+                        |> Sequence.to_list
+                      in
+                      let error_attached =
+                        match collected_errors with
+                        | [] ->
+                            Error.of_string "In progress"
+                        | errors ->
+                            Error.of_list errors
```
Comment (glyh) [inline src/lib/network_pool/batcher.ml:420]: All errors are aggregated. That said. I'm not sure should we prune some of these so that the logs are not growing infinitely.

**Comment by glyh** [comment]
Actually, this is breaking, rebasing against develop.

EDIT: it's breaking only if verifier & daemon endpoints are using different binraries, which is unlikely. However, since we're testing on mesa, rebasing against develop should be just fine?

File: src/lib/network_pool/batcher.ml [hunk 2]
```diff
@@ -402,15 +403,31 @@ module Transaction_pool = struct
...
+                             | `Valid_assuming (_, _, err) ->
+                                 Some err
+                             | _ ->
+                                 None )
+                        |> Sequence.to_list
+                      in
+                      let error_attached =
+                        match collected_errors with
+                        | [] ->
+                            Error.of_string "In progress"
```
Comment (glyh) [inline src/lib/network_pool/batcher.ml:418]: I think it still make sense to keep this case when there's no error.

Comment (glyh) [reply src/lib/network_pool/batcher.ml:418]: But further refactor setting this to an Error.t option would also be preferred.

**Comment by cjjdespres** [comment]
I think the external verifier is created by the daemon using the exact same binary used to run the daemon, with `async_parallel`. So I don't think daemon-verifier interface changes will be breaking on their own. 

More historical context, just for general interest: similar issue was brought up in https://github.com/MinaProtocol/mina/discussions/17766, https://github.com/MinaProtocol/mina/issues/17834, https://github.com/MinaProtocol/mina/issues/17818.

**Review by georgeee — APPROVED** [review]
Any particular reason to target `develop` and not `compatible`? Otherwise looks good!

**Comment by georgeee** [comment]
> Actually, this is breaking, rebasing against develop.
> 
> EDIT: it's breaking only if verifier & daemon endpoints are using different binraries, which is unlikely. However, since we're testing on mesa, rebasing against develop should be just fine?

Yes, let's target `compatible`. Because it's guaranteed that the same executable is used, there is no backwards-compatibility concerns involved.

**Comment by glyh** [comment]
Okay, rebased back to compatible

**Comment by georgeee** [comment]
!ci-build-me

**Comment by amc-ie** [comment]
!ci-bypass-changelog
