### PR TITLE
fix #6542

### LINKED ISSUE #6542: propagate errors from ledger_transfer to epoch ledger sync
Deepthi pointed out the following flaws in current epoch_ledger_persistence implementation.

Currently we are ignoring errors when doing ledger_transfer:
https://github.com/MinaProtocol/mina/blob/dc924117ac4ea69d036384649a1a274c44803554/src/lib/consensus/proof_of_stake.ml#L437
https://github.com/MinaProtocol/mina/blob/dc924117ac4ea69d036384649a1a274c44803554/src/lib/consensus/proof_of_stake.ml#L449

We should instead propagate the errors to `sync_local_state`, which means if ledger_transfer fails we should simply punish the peer and try another one.

Another thing is that we should check ledger_depth of the sparse ledger that the peer send to us before we try do the ledger_transfer.

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
This PR propagate errors from ledger_transfer to epoch-ledger sync. If the transfer fails it would try another peer.

Closes #6542

### CODE REVIEW

File: src/lib/consensus/proof_of_stake.ml [hunk 1]
```diff
@@ -2657,15 +2660,26 @@ module Hooks = struct
               query_peer.query peer Rpcs.Get_epoch_ledger
                 (Coda_base.Frozen_ledger_hash.to_ledger_hash target_ledger_hash)
             with
-            | Connected {data= Ok (Ok sparse_ledger); _} ->
+            | Connected {data= Ok (Ok sparse_ledger); _} -> (
                 let%bind () =
                   Trust_system.(
                     record trust_system logger peer
```
Comment (deepthiskumar) [inline src/lib/consensus/proof_of_stake.ml:2666]: Should we record this only if it provides a valid epoch ledger?

**Review by deepthiskumar — APPROVED** [review]
Looks good!
