### PR TITLE
Explain some terminating signals

### LINKED ISSUE #7620: Add exit code to child process logs when they exit to help debug nodes crashing during first catchup
This would help verify if they're being killed from memory pressure, if the code turns out to be 137

Recent example:

{"timestamp":"2021-01-22 09:41:55.394467Z","level":"Info","source":{"module":"Dune__exe__Coda","location":"File \"src/app/cli/src/coda.ml\", line 491, characters 16-27"},"message":"Daemon child process $child_pid terminated after receiving signal $signal","metadata":{"$duplicated_keys":["host","peer_id","port"],"child_pid":73,"host":"34.70.183.242","peer_id":"12D3KooWDqXFAw3JEZji5Qj2rUaUeLyz2CkcN1UYuKms6wNy7iRr","pid":12,"port":10507,"signal":"sigkill"}}

{"timestamp":"2021-01-22 09:41:55.394535Z","level":"Error","source":{"module":"Child_processes__Termination","location":"File \"src/lib/child_processes/termination.ml\", line 31, characters 6-18"},"message":"Child process of kind $process_kind with pid $child_pid has terminated","metadata":{"$duplicated_keys":["host","peer_id","port"],"child_pid":73,"host":"34.70.183.242","peer_id":"12D3KooWDqXFAw3JEZji5Qj2rUaUeLyz2CkcN1UYuKms6wNy7iRr","pid":12,"port":10507,"process_kind":"Prover"}}

### PR DESCRIPTION
**Pull request by psteckler**
For some signals (namely, SIGKILL and SIGINT), log a possible cause when a child process terminates. 

There's an extensible table of signals-to-causes, if more such signals have plausible explanations.

Closes #7620.

### CODE REVIEW

File: src/app/cli/src/coda.ml [hunk 1]
```diff
@@ -493,7 +493,12 @@ let setup_daemon logger =
                    signal $signal"
                   ~metadata:
                     ( ("signal", `String (Signal.to_string signal))
-                    :: child_pid_metadata )
+                    :: child_pid_metadata ) ;
+                Option.value_map
+                  (Child_processes.Termination.get_signal_cause_opt signal)
+                  ~default:() ~f:(fun cause ->
+                    [%log info] "Possible reason signal caused termination"
```
Comment (mrmr1993) [inline src/app/cli/src/coda.ml:500]: Should this be at level `error` instead? Also, `:` after `possible reason`

Comment (psteckler) [reply src/app/cli/src/coda.ml:500]: The other log messages here about termination are at `info` level. Should that change?

I meant the text as, "the possible reason that the signal caused termination".

Comment (mrmr1993) [reply src/app/cli/src/coda.ml:500]: `Possible reason for signal: $cause` may be clearer, and will show the cause it the pretty logs

File: src/lib/child_processes/termination.ml [hunk 2]
```diff
@@ -24,6 +24,17 @@ let mark_termination_as_expected t child_pid =
 
 let remove : t -> Pid.t -> unit = Pid.Table.remove
 
+(* for some signals that cause termination, offer a possible explanation *)
+let get_signal_cause_opt =
+  let open Signal in
+  let signal_causes_tbl : string Table.t = Table.create () in
+  List.iter
+    [ (kill, "Process likely killed because out of memory")
```
Comment (mrmr1993) [inline src/lib/child_processes/termination.ml:32]: You can remove `likely` here, since the wrapping error message already says `possible`

**Review by mrmr1993 — APPROVED** [review]
