### PR TITLE
Hardfork package generation automation

### LINKED ISSUE #15152: Global slot offset incorrect when generating HF package
The hardfork package generation pipeline is always using the mainnet genesis timestamp when computing the new network's genesis slot offset. The hardfork package generation pipeline should instead use the genesis timestamp for the network we are forking from.

### LINKED ISSUE #15153: Generate HF packages for testnets
The hardfork package generation pipeline is always generating builds for mainnet signatures. The signature type should be configured based on the network we are forking from.

### PR DESCRIPTION
**Pull request by nholland94**
NB: This PR is based on (and includes some work from) #15003, but has been rebased onto the latest berkeley, so the commits were re-written. I think the best thing to do here is to disentangle these 2 PRs. Only some of the scripts added in #15003 were used in this PR, so what I might do is just keep those and throw out the other commits. For now, this PR is a draft.

This PR enables a new pipeline in buildkite for generating hardfork packages and releases from those packages. The pipeline can be executed on-demand and is not intended to be enabled on a per-PR basis. You can play with the pipeline here in my test buildkite pipeline, which will be migrated into an official hardfork pipeline once this is merged. https://buildkite.com/o-1-labs-2/nathans-test-pipeline.

To execute a build, you must provide specific environment variables. Below is a sample of environment variables you can provide.

```
BUILDKITE_PIPELINE_MODE=PackageGeneration
BUILDKITE_PIPELINE_FILTER=Release
NETWORK_NAME=berkeley
CONFIG_JSON_GZ_URL=https://storage.googleapis.com/tmp-hardfork-testing/fork_config_hf_test_3_fixed.json.gz
# optional: GENESIS_TIMESTAMP=...
```

The `BUILDKITE_PIPELINE_MODE` and `BUILDKITE_PIPELINE_FILTER` variables select the correct jobs for hardfork pipeline (we can configure the hardfork pipeline to set these env vars these automatically). The `DUNE_PROFILE` var will set the profile to build for, allowing you to target a hardfork for a devnet or mainnet. The `CONFIG_JSON_GZ_URL` var provides a location to a gzipped json file dumped from the previous network. The json must contain the fork_config and ledger accounts for the genesis ledger and epoch ledgers we are forking from.

In order to support new jobs that will only be spawned on-demand an not per-PR, I added a new pipeline mode to the dhall configuration called `PackageGeneration`. This is only used by the hardfork package generation at the moment, but can be extended to other package generation jobs. The semantics of this pipeline mode is that it won't be included on a PR pipeline, but can be included if the `BUILDKITE_PIPELINE_MODE` var is set to `PackageGeneration`. The existing `MinaArtifact*` jobs are still configured to use the `PullRequest` mode.

PENDING TODOS:
- support setting tags that don't get suffixed with `-hardfork`

UNSUPPORTED WORKFLOWS:
- does not support lightnet

Closes #15153.
Closes #15152.

### CODE REVIEW

File: buildkite/scripts/build-hardfork-package.sh [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+# NB: we use sed here instead of jq, because jq is extremely slow at processing this file
+sed -i -e 's/"set_verification_key": "signature"/"set_verification_key": {"auth": "signature", "txn_version": "1"}/' config.json
+
+echo "--- Build libp2p_helper"
+make -C src/app/libp2p_helper
+
+MAINNET_TARGETS=""
+[[ ${MINA_BUILD_MAINNET} ]] && MAINNET_TARGETS="src/app/cli/src/mina_mainnet_signatures.exe src/app/rosetta/rosetta_mainnet_signatures.exe src/app/rosetta/ocaml-signer/signer_mainnet_signatures.exe"
+
+echo "--- Build all major tagets required for packaging"
```
Comment (dkijania) [inline buildkite/scripts/build-hardfork-package.sh:28]: This duplicated build-artifacts.sh script. Was there any reason not to reuse this part? Are all binaries needed for hardfor package generation?

File: dockerfiles/Dockerfile-mina-daemon [hunk 2]
```diff
@@ -58,7 +58,7 @@ RUN apt-get update --quiet --yes \
 RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
   && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - \
   && apt-get update --quiet --yes \
-  && apt-get install --quiet --yes --no-install-recommends google-cloud-sdk kubectl google-cloud-sdk-gke-gcloud-auth-plugin \
+  && apt-get install --quiet --yes --no-install-recommends google-cloud-sdk=462.0.1-0 kubectl=1:462.0.1-0 google-cloud-sdk-gke-gcloud-auth-plugin=462.0.1-0 \
```
Comment (dkijania) [inline dockerfiles/Dockerfile-mina-daemon:61]: Can we comment here why we are sticking to particular commits?

File: buildkite/src/Pipeline/Mode.dhall [hunk 3]
```diff
@@ -5,16 +5,17 @@
 
 let Prelude = ../External/Prelude.dhall
 
-let Mode = < PullRequest | Stable >
+let Mode = < PullRequest | Stable | PackageGeneration >
```
Comment (dkijania) [inline buildkite/src/Pipeline/Mode.dhall:8]: Pipeline mode was originally designed for organizing pipelines based on frequency of runs or stage in which pipeline should . Here i think package generation pipeline is ran before hardfork, or frequently once per week. I would reflect that in name and not to mention purpose of pipeline mode

**Review by dkijania — COMMENTED** [review]
From CI perspective it looks like there are a quite a few duplications and new very special behavior for hardfork generation. I would love to see them incorporated in scripts and dhall files so there is no special treatment for hardfork generation jobs

File: dockerfiles/Dockerfile-mina-daemon (hunk 2 above)
Comment (nholland94) [reply dockerfiles/Dockerfile-mina-daemon:61]: This was a hack to get around the google version issue that was blocking docker builds last week. I put this hack in here before the actual fix was merged into upstream branches. I'll try removing now and see if the upstream fixes worked or not.

File: buildkite/src/Pipeline/Mode.dhall (hunk 3 above)
Comment (nholland94) [reply buildkite/src/Pipeline/Mode.dhall:8]: Pipeline mode seems to be designed for selecting which pipeline something should be a part of, based on reading the code that filtering pipelines based on their mode. The PackageGeneration is not run on an interval, it is only run on-demand, so I've put it in it's own mode and updated the selection logic accordingly. Are you saying this is not the correct usage of the pipeline mode? I didn't quite understand your point about pipeline mode being for specifying the frequency or stage, can you expand more on that?

**Comment by nholland94** [comment]
> From CI perspective it looks like there are a quite a few duplications and new very special behavior for hardfork generation. I would love to see them incorporated in scripts and dhall files so there is no special treatment for hardfork generation jobs

Can you provide examples of what you would like to see specifically? All of the scripts that were added build on top of the existing scripts for doing deb releases, and for the most part, are only adding additional logic on top of that which only happens in the case of hardforks. The only source of duplication I see is the new MinaArtifact pipeline, but enough is different about the workflow for how env vars and other params are passed that I didn't think it made sense to share the code between the 2 pipelines. They still share underlying scripts.

File: src/lib/genesis_ledger_helper/genesis_ledger_helper.ml [hunk 4]
```diff
@@ -168,9 +171,9 @@ module Ledger = struct
                   ] ;
               return None )
       | None ->
-          [%log warn]
+          [%log error]
```
Comment (emberian) [inline src/lib/genesis_ledger_helper/genesis_ledger_helper.ml:174]: pls unrevert this log level + msg change- we don't want this to be an `error` until the rest of the logic is fixed to not try downloading when an explicit account list is provided.

File: buildkite/src/Pipeline/Mode.dhall (hunk 3 above)
Comment (dkijania) [reply buildkite/src/Pipeline/Mode.dhall:8]: Apologies i wasn't clear enough. In my previous comment i referred to frequency of runs but it is not relevant mode of pipeline. My understanding of pipeline mode is that it is basically a strategy according which we should pick up the jobs to be ran within pipeline. 

Initially 

| Pull Request | Stable |
| -----------------| ---------- |
| all defined **dirty** jobs | all defined jobs |


I've implemented Filtering mechanism some time a go which added more complexity and currently above modes can be translated to


| Pull Request | Stable |
| -----------------| ---------- |
| all defined **dirty** jobs tagged according to input filter | all defined jobs tagged according to input filter |

I think that PackageGeneration does not introduced another mode. It just uses Stable mode logic. The difference is only in used filter. 

It was my mistake not to rename properly modes after i added filtering stuff. It would be my pleasure to do it in separate PR on within this one. I think more adequate names would be Triaged or DirtyOnly  |  Filtered . Then such pipeline would be ran with env variables:

```
BUILDKITE_PIPELINE_MODE=Filtered
BUILDKITE_PIPELINE_FILTER=Release
```

File: buildkite/src/Pipeline/Filter.dhall [hunk 5]
```diff
@@ -15,6 +15,7 @@ let tags: Filter -> List Tag.Type = \(filter: Filter) ->
     , TearDownOnly = [ Tag.Type.TearDown ]
     , ToolchainsOnly = [ Tag.Type.Toolchain ]
     , AllTests = [ Tag.Type.Lint, Tag.Type.Release, Tag.Type.Test ]
+    , Release = [ Tag.Type.Release ]
```
Comment (dkijania) [inline buildkite/src/Pipeline/Filter.dhall:18]: I think you forgot to add Release tag in tag.dhall file

File: scripts/deb-builder-helpers.sh [hunk 6]
```diff
@@ -0,0 +1,192 @@
...
+set -euo pipefail
+
+SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
+cd "${SCRIPTPATH}/../_build"
+
+GITHASH=$(git rev-parse --short=7 HEAD)
+GITHASH_CONFIG=$(git rev-parse --short=8 --verify HEAD)
+
+set +u
+BUILD_NUM=${BUILDKITE_BUILD_NUM}
```
Comment (dkijania) [inline scripts/deb-builder-helpers.sh:16]: this script is outside buildkite folder so IMHO it should not know about any buildkite existence

**Comment by dkijania** [comment]
> Can you provide examples of what you would like to see specifically? 

buildkite/scripts/build-hardfork-package.sh -  this one builds packages in the very same way as build-artifacts. 
buildkite/src/Command/MinaArtifact.dhall - two pipelines sharing a lot of setup. You already responded that you don't see point in removing duplication. IMHO i see a point as this is most important job in entire CI + also make sense to implement your comments above. Again, maybe not as a part of this pr
scripts/deb-builder-helpers.sh - this is nice that you extracted deb builder helper. But still archive deb uses it's own script to build it. EDIT: actually after my changes on which you can rebase those are using single script now.

File: src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml [hunk 7]
```diff
@@ -2,56 +2,84 @@ open Core
 open Async
 module Ledger = Mina_ledger.Ledger
 
-type t = Ledger.t
-
-module Hash_json = struct
-  type epoch_data = { staking_hash : string; next_hash : string option }
+module Hashes = struct
+  type t = { s3_data_hash : string; ledger_hash : string }
```
Comment (georgeee) [inline src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml:6]:
```suggestion
  type t = { s3_data_hash : string; hash : string }
```

This suggestion would be necessary to unlock another suggestion/simplification above.

File: src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml [hunk 8]
```diff
@@ -2,56 +2,84 @@ open Core
...
   [@@deriving to_yojson]
+end
 
-  type t = { genesis_hash : string; epoch_data : epoch_data option }
+module Hash_json = struct
+  type t = { genesis : Hashes.t; staking : Hashes.t; next_staking : Hashes.t }
```
Comment (georgeee) [inline src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml:11]:
```suggestion
  type epoch_data = { staking : Hashes.t; next : Hashes.t option }
  type t = { ledger : Hashes.t; epoch_data: epoch_data option }
```



with

```
module Epoch_data = { staking : Hashes.t; next : Hashes.t option }
```

**Review by georgeee — CHANGES_REQUESTED** [review]
Current implementastion seems not to handle case of no `next` ledger well (which might be a case we see in production). I've left a few comments, but would suggest syncing https://github.com/MinaProtocol/mina/blob/georgeee/tmp-branch-for-berkeley-scripts-testing/src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml from another branch and modifying the `create_runtime_config.sh` script.

File: buildkite/src/Pipeline/Mode.dhall (hunk 3 above)
Comment (nholland94) [reply buildkite/src/Pipeline/Mode.dhall:8]: What I want at the end of the day is a way to filter out only the hardfork release jobs. I don't want the other jobs to run, and these hardfork jobs will never run in a PR.

**Comment by nholland94** [comment]
I commented on this offline, but just to make sure it's tracked in this discussion.

> Current implementastion seems not to handle case of no next ledger well (which might be a case we see in production).

We will always have staking and next_staking ledgers, so that's not a real edge case. The edge case is that they may all point to the same merkle root.

File: scripts/deb-builder-helpers.sh (hunk 6 above)
Comment (nholland94) [reply scripts/deb-builder-helpers.sh:16]: The existing `scripts/rebuild-deb.sh` also has this reference even after your recent refactor. I'd prefer to make this change in another PR, as it's unrelated to this work and has been this way int he code for some time now.

File: buildkite/src/Pipeline/Filter.dhall (hunk 5 above)
Comment (nholland94) [reply buildkite/src/Pipeline/Filter.dhall:18]: There was already a `Tag.Type.Release` before my PR, you can see it was previously referenced in the line above this.

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-nightly-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Comment by georgeee** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

**Review by dkijania — APPROVED** [review]
Approving, since we had a deal to refactor CI later

**Review by georgeee — APPROVED** [review]

**Review by georgeee — APPROVED** [review]

**Comment by nholland94** [comment]
!ci-build-me

**Comment by nholland94** [comment]
!ci-build-me

File: buildkite/scripts/build-hardfork-package.sh [hunk 9]
```diff
@@ -2,7 +2,23 @@
 
 set -eo pipefail
 
-([ -z ${DUNE_PROFILE+x} ] || [ -z ${CONFIG_JSON_GZ_URL+x} ] || [ -z ${NETWORK_NAME+x} ] || [ -z ${MINA_DEB_CODENAME+x} ]) && echo "required env vars were not provided" && exit 1
+# TODO: remove DUNE_PROFILE and configure using NETWORK_NAME
```
Comment (georgeee) [inline buildkite/scripts/build-hardfork-package.sh:5]: Is this TODO still to be here or could be removed?

**Review by georgeee — APPROVED** [review]

File: buildkite/scripts/build-hardfork-package.sh (hunk 9 above)
Comment (nholland94) [reply buildkite/scripts/build-hardfork-package.sh:5]: Woops, I thought I did already. Fixing.

**Comment by nholland94** [comment]
!ci-build-me
