### PR TITLE
Remove offline timeout shutdown, log instead

### LINKED ISSUE #7970: Stop crashing the daemon when it is offline for 15-mins?

### PR DESCRIPTION
**Pull request by psteckler**
Remove the code that starts a shutdown timer when a node is `Offline`.

Tested that the sync status still updates with `client status` on a local network.

Closes #7970.

### CODE REVIEW

**Review by nholland94 — CHANGES_REQUESTED** [review]
We discussed adding an error log in place of the shutdown. Can we still do that? We can keep that error silent if `is_seed` is true.

**Comment by psteckler** [comment]
> We discussed adding an error log in place of the shutdown.

Yes, can put that in.

**Review by deepthiskumar — CHANGES_REQUESTED** [review]
Instead of crashing we want to add an error log saying the node was offline for 15 mins and suggest checking if they have forwarded the port correctly

File: src/lib/mina_lib/mina_lib.ml [hunk 1]
```diff
@@ -401,6 +401,44 @@ let create_sync_status_observer ~logger ~demo_mode ~net
...
+          offline_timeout :=
+            Some
+              (Timeout.create () offline_timeout_duration
+                 ~f:log_offline_warning)
+    in
+    let stop_offline_timeout () =
+      match !offline_timeout with
+      | Some timeout ->
+          Timeout.cancel () timeout () ;
+          offline_timeout := None
```
Comment (nholland94) [inline src/lib/mina_lib/mina_lib.ml:427]: If the timeout had already triggered by this point, would be nice to give an info log saying that the node is now back online.

**Comment by psteckler** [comment]
@nholland94 @deepthiskumar Made requested changes, I believe.

**Comment by jrwashburn** [comment]
I really prefer this something that can be enabled/disabled from coda client CLI. Other than the unique edge case bootstrapping a new network, when is this actually valuable? I prefer termination to hanging out offline relatively quietly. Why is it good to stay up, offline?

**Comment by nholland94** [comment]
> I really prefer this something that can be enabled/disabled from coda client CLI. Other than the unique edge case bootstrapping a new network, when is this actually valuable? I prefer termination to hanging out offline relatively quietly. Why is it good to stay up, offline?

Having nodes crash after 15 minutes of inactivity on the network has the effect that the entire network can crash if no one is producing blocks or sending transactions for 5 slots. That's a bad thing, and we never want that to happen, but this behavior means that the network will just shut down if that happens, which only makes things worse. Note that your node will still crash if it cannot connect to peers. It's only that now it will not crash if the network has been silent for a few slots.

**Review by nholland94 — APPROVED** [review]

**Review by deepthiskumar — APPROVED** [review]

**Comment by aneesharaines** [comment]
!approved-for-mainnet
