### PR TITLE
sync local state even if we can't download best tip from peers

### LINKED ISSUE #8660: Mina node did not change staking ledger at start of third epoch (#2)
After the beginning of the third epoch (epoch=2), one of our mina nodes failed to change its staking ledger from the genesis ledger yet still reported a sync status of "Synced" and maintained its block height inline with the network.

All nodes were running the docker image "docker.io/minaprotocol/mina-daemon-baked:1.1.4-a8893ab" with image id "1239c3c492fa".

mina version reports "Commit a8893ab6dd8a68171e7b99a5dc6b76940411350b on branch master" on all nodes.

The "?-output-hash.txt" files contain the output of "mina ledger hash" run on the respective node's staking epoch ledger.

**Attached files beginng with "0-" relate to the affected node.**
[0-output-hash.txt](https://github.com/MinaProtocol/mina/files/6321025/0-output-hash.txt)
[0-output-next-epoch-ledger.txt](https://github.com/MinaProtocol/mina/files/6321026/0-output-next-epoch-ledger.txt)
[0-output-staged-ledger.txt](https://github.com/MinaProtocol/mina/files/6321027/0-output-staged-ledger.txt)
[0-output-staking-epoch-ledger.txt](https://github.com/MinaProtocol/mina/files/6321028/0-output-staking-epoch-ledger.txt)
[0-output-status.txt](https://github.com/MinaProtocol/mina/files/6321029/0-output-status.txt)

**Attached files beginning with "1-" relate to another that is running normally.**
[1-output-hash.txt](https://github.com/MinaProtocol/mina/files/6321030/1-output-hash.txt)
[1-output-next-epoch-ledger.txt](https://github.com/MinaProtocol/mina/files/6321031/1-output-next-epoch-ledger.txt)
[1-output-staged-ledger.txt](https://github.com/MinaProtocol/mina/files/6321032/1-output-staged-ledger.txt)
[1-output-staking-epoch-ledger.txt](https://github.com/MinaProtocol/mina/files/6321033/1-output-staking-epoch-ledger.txt)
[1-output-status.txt](https://github.com/MinaProtocol/mina/files/6321034/1-output-status.txt)

**Compressed stdout log from affected node container**
[20210415-215911-c-mina-mainnet-main.log.gz](https://github.com/MinaProtocol/mina/files/6321353/20210415-215911-c-mina-mainnet-main.log.gz)

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
I ran a node connected to the mainnet to test it. https://github.com/MinaProtocol/mina/pull/8778

Closes #8660

### CODE REVIEW

File: src/lib/transition_router/transition_router.ml [hunk 1]
```diff
@@ -317,12 +317,44 @@ let initialize ~logger ~network ~is_seed ~is_demo_mode ~verifier ~trust_system
...
          network; starting participation" ;
-      return
-      @@ start_transition_frontier_controller ~logger ~trust_system ~verifier
-           ~network ~time_controller ~producer_transition_reader_ref
-           ~producer_transition_writer_ref ~verified_transition_writer
-           ~clear_reader ~collected_transitions:[] ~transition_reader_ref
-           ~transition_writer_ref ~frontier_w ~precomputed_values frontier
+      let curr_best_tip = Transition_frontier.best_tip frontier in
+      let%map () =
+        match
```
Comment (deepthiskumar) [inline src/lib/transition_router/transition_router.ml:322]: move this to a separate function since we do the same for the catchup case below?

File: src/lib/transition_router/transition_router.ml [hunk 2]
```diff
@@ -423,9 +390,8 @@ let initialize ~logger ~network ~is_seed ~is_demo_mode ~verifier ~trust_system
         start_transition_frontier_controller ~logger ~trust_system ~verifier
           ~network ~time_controller ~producer_transition_reader_ref
           ~producer_transition_writer_ref ~verified_transition_writer
-          ~clear_reader ~collected_transitions:[best_tip]
-          ~transition_reader_ref ~transition_writer_ref ~frontier_w
-          ~precomputed_values frontier )
+          ~clear_reader ~collected_transitions:[] ~transition_reader_ref
```
Comment (deepthiskumar) [inline src/lib/transition_router/transition_router.ml:393]: In the case a best tip is downloaded, you want that to be passed here, right?

**Review by deepthiskumar — APPROVED** [review]
