### PR TITLE
Small package of fixes for migration process

### LINKED ISSUE #14551: Deploy Archive Migration Tool
### Deploy Archive Migration tools 

Archive Migration tooling consist of two applications:

- berkeley_migration (#12906)
- berkeley_account_tables (#14339)

We need to incorporate deployment of above apps into actual process. Basically the idea is to add above apps to build step in CI and pack them together with mina archive debian package as well as docker,

### PR DESCRIPTION
**Pull request by dkijania**
Archive Migration tooling consist of two applications:

- berkeley_migration (#12906)
- berkeley_account_tables (#14339)

During testing I found a couple of improvements/ small fixes which are necessary for testing and correct run:
- extract parameters from berkeley_migration:
   a) bucket location
   b) number of batches for precomputed block fetch
   c) corner case when there are no precomputed blocks to fetch 

Closes #14551

### CODE REVIEW

**Comment by dkijania** [comment]
ci-build-me!

**Comment by psteckler** [comment]
Did you see my message about writing the migrated transaction hashes?

When migrated, the old transaction hashes will be written as new transaction hashes. In my message, I explained how to avoid that.

You might want to add a check that the migrated transaction hashes are syntactically the same as the old ones.

File: src/app/berkeley_migration/berkeley_migration.ml [hunk 1]
```diff
@@ -142,7 +143,7 @@ let user_commands_from_block_id ~mainnet_pool block_id =
           ~f:mainnet_transaction_failure_of_string
       in
       let hash =
-        Mina_transaction.Transaction_hash.of_base58_check_exn user_cmd.hash
+        Mina_transaction.Transaction_hash.of_base58_check_exn_v1 user_cmd.hash
```
Comment (ghost-not-in-the-shell) [inline src/app/berkeley_migration/berkeley_migration.ml:146]: I think you should also change in archive_lib.user_commands.add_extensional_if_doesn't_exist function. Otherwise the hash you writen to the migrated database would be changed: https://github.com/MinaProtocol/mina/blob/79c6253989ddaa0db2c4c7267f3dc1a5bf9f12e9/src/app/archive/lib/processor.ml#L1882

I am not sure

**Comment by ghost-not-in-the-shell** [comment]
I agree with paul that you want to add some check that checks the migrated transaction hash is syntactically the same as before.

File: src/app/berkeley_migration/berkeley_migration.ml (hunk 1 above)
Comment (psteckler) [reply src/app/berkeley_migration/berkeley_migration.ml:146]: I sent an email to Deepthi with a suggested way to handle this issue. You'd add an optional boolean flag to `add_extensional_if_doesn't_exist` that would indicate whether to use the `V1` hash.

**Review by ghost-not-in-the-shell — APPROVED** [review]

**Comment by dkijania** [comment]
!ci-build-me

File: src/app/archive/lib/processor.ml [hunk 2]
```diff
@@ -34,6 +34,13 @@ let applied_str = "applied"
 
 let failed_str = "failed"
 
+let to_base58_check ?(v1_transaction_hash = false) hash =
+  match v1_transaction_hash with
```
Comment (psteckler) [inline src/app/archive/lib/processor.ml:38]: `if ... then ... else` might be simpler than `match` here

**Review by Trivo25 — APPROVED** [review]

**Comment by ghost-not-in-the-shell** [comment]
!ci-build-me

**Comment by ghost-not-in-the-shell** [comment]
!ci-nightly-me

**Comment by deepthiskumar** [comment]
!approved-for-mainnet

**Review by dannywillems — APPROVED** [review]
Bumping protocol team approval.
