### PR TITLE
Fix flaky runtime fixed id collision test 

### LINKED ISSUE #14746: Fix (rarely) flaky test: fixed & runtime table ID/first column collision
`pickles_test_optional_custom_gates.ml` sometimes (rarely) fails, which shows more often if parameters of the test are changed to smaller ones.

Basically, runtime and fixed table IDs can collide, BUT if a `Lookup` is requested in both fixed setup and runtime setup, and this lookup requests the same key with two different values, only the latter value will be actually written into the lookup table (https://github.com/MinaProtocol/mina/blob/develop/src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml#L1902), which in practice will lead to an unsatisfiable circuit that will fail with ValueNotInTable(i).

The issue can be reproduced in the following way:
* add a fixed lookup table with id = 1, keys 0..4, and 5 random values
* add a runtime lookup table with id = 1, keys (first_column) 0..4. I also generate a vector second_row of size 5 with some random values.
* make 100 random lookup queries to the fixed table.
* make 100 random lookup queries to the runtime table using `(k,v = second_column[k])`
* observe `ValueNotInTable`

### PR DESCRIPTION
**Pull request by volhovm**
Fixes #14746 by adding a test setup step which makes sure no colliding keys with different values exist between runtime and fixed tables if their table ids collide.

### CODE REVIEW

**Comment by volhovm** [comment]
!ci-build-me

**Comment by volhovm** [comment]
Ran the test several times locally with both small and big parameters, seems that the flaky-bug fix works. I mark it as ready for the review.

File: src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml [hunk 1]
```diff
@@ -1899,6 +1899,11 @@ end = struct
         let lookup3 = (red_w0, (red_w5, red_w6)) in
         (* We populate with the first lookup. In the case the user uses the same
            index multiple times, the last value will be used *)
+        (* @volhovm: perhaps it would be better if runtime_lookups_rev was a set
```
Comment (mrmr1993) [inline src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml:1902]: I would prefer not to include this.

File: src/lib/pickles/test/optional_custom_gates/pickles_test_optional_custom_gates.ml [hunk 2]
```diff
@@ -236,92 +236,145 @@ let main_fixed_lookup_tables () =
...
-      , (idx1, values.(idx1))
-      , (idx2, values.(idx2))
-      , (idx3, values.(idx3)) ) )
+      , (indices.(idx1), values.(idx1))
+      , (indices.(idx2), values.(idx2))
+      , (indices.(idx3), values.(idx3)) ) )
 
 let main_fixed_lookup_tables_multiple_tables_multiple_lookups () =
-  Array.iter fixed_lt_data ~f:(fun (table_id, indexes, values) ->
+  Array.iter fixed_lt_data ~f:(fun (table_id, indices, values) ->
```
Comment (mrmr1993) [inline src/lib/pickles/test/optional_custom_gates/pickles_test_optional_custom_gates.ml:283]: Nit: correct, but not common usage in code

**Review by mrmr1993 — APPROVED** [review]
LGTM, but see nits

File: src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml (hunk 1 above)
Comment (volhovm) [reply src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml:1902]: Would creating an issue with this task description be a better option?

File: src/lib/pickles/test/optional_custom_gates/pickles_test_optional_custom_gates.ml (hunk 2 above)
Comment (volhovm) [reply src/lib/pickles/test/optional_custom_gates/pickles_test_optional_custom_gates.ml:283]: Will revert to `indexes` then + remove that comment.

**Comment by volhovm** [comment]
!ci-build-me

File: src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml (hunk 1 above)
Comment (volhovm) [reply src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml]: Created https://github.com/MinaProtocol/mina/issues/14749

**Comment by volhovm** [comment]
!ci-build-me
