### PR TITLE
prevent more restarts when is_seed

### LINKED ISSUE #15056: Do not shutdown when offline if the node is a seed
The `-seed` flag informs the running node that it should not shutdown if it fails to find initial peers when starting up. However, as the code is currently, a seed node may still shutdown if it is offline for too long. This can make it more difficult to recover networks, as the seed nodes need to be online to fix the network by allowing new nodes to join and continue gossip again. We should modify the code such that the offline shutdown logic is skipped if the node is a seed node.

### PR DESCRIPTION
**Pull request by emberian**
Closes #15056

### CODE REVIEW

**Review by nholland94 — APPROVED** [review]

File: src/lib/mina_lib/mina_lib.ml [hunk 1]
```diff
@@ -479,7 +479,7 @@ let create_sync_status_observer ~logger ~is_seed ~demo_mode ~net
           match online_status with
           | `Offline ->
               (* nothing to do if offline before genesis *)
-              ( if after_genesis () then
+              ( if (not is_seed) && after_genesis () then
```
Comment (nholland94) [inline src/lib/mina_lib/mina_lib.ml:482]: I think this check should be moved further down. If the node is a seed node, we should still attempt the libp2p_helper restart when it's offline, but we shouldn't schedule the offline shutdown. I think adding a check before the match statement on line 493 would work better.

**Review by nholland94 — CHANGES_REQUESTED** [review]

**Comment by nholland94** [comment]
Sorry, changed my mind :P

**Review by nholland94 — APPROVED** [review]

**Comment by emberian** [comment]
!ci-build-me
