### PR TITLE
[Trivial] Improve error message from missing --generate-genesis-proof

### LINKED ISSUE #8093: Missing -generate-genesis-proof flag throws an ugly error
Crash_log 

{"OS_type":"Unix","Release":"5.4.0-1037-gcp","Machine":"x86_64","Sys_name":"Linux","Exception":{"commit_id":"fd3980820fb82c7355af49462ffefe6718800b77","sexp":["monitor.ml.Error","No genesis proof file was found and not allowed to generate a new genesis proof",["Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30","Called from file \"src/app/cli/src/mina.ml\", line 653, characters 12-27","Called from file \"src/deferred1.ml\", line 17, characters 40-45","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47","Caught by monitor coda"]],"backtrace":["Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30","Called from file \"src/app/cli/src/mina.ml\", line 653, characters 12-27","Called from file \"src/deferred1.ml\", line 17, characters 40-45","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47"]},"Command":"Command: (mina daemon)","Coda_branch":"master","Coda_commit":"fd3980820fb82c7355af49462ffefe6718800b77"}
~

### PR DESCRIPTION
**Pull request by mrmr1993**
This now prints
```

FATAL ERROR

  ☠  Coda Daemon encountered a configuration error generating a genesis proof.

Hint: pass the flag --generate-genesis-proof true. For example,
mina.exe daemon --generate-genesis-proof true
```

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

Closes #8093

### CODE REVIEW

File: src/lib/genesis_ledger_helper/genesis_ledger_helper.ml [hunk 1]
```diff
@@ -1084,9 +1084,13 @@ module Genesis_proof = struct
...
-        Deferred.Or_error.errorf
-          "No genesis proof file was found and not allowed to generate a new \
-           genesis proof"
+        Deferred.Or_error.of_exn
+          (Mina_user_error.Mina_user_error
+             { where= Some "generating a genesis proof"
+             ; message=
+                 "Hint: pass the flag --generate-genesis-proof true. For \
+                  example,\n\
+                  mina.exe daemon --generate-genesis-proof true" })
```
Comment (psteckler) [inline src/lib/genesis_ledger_helper/genesis_ledger_helper.ml:1093]: I think the executable is just `mina` in distributed containers.

Could you use argv[0] here?

**Review by psteckler — APPROVED** [review]
one nit

**Comment by aneesharaines** [comment]
!approved-for-mainnet
