### PR TITLE
Fix problems with balance reconciliation in rosetta-cli tests

### LINKED ISSUE #12299: Fix wrong balances reported by Rosetta
When asked about an account's balance at a particular block, Rosetta mis-reports the balance if that account hasn't been involved in any transactions before that block. In particular, it returns the most recent balance instead of the genesis balance for the account. The gensis balance is not currently available to Rosetta, so the idea is to expose it through GraphQL. The genesis ledger can be loaded from the configuration file, so any node should posses it readily available.

We should make sure that data is reliable though, i.e. whether a node having wrong genesis ledger would be rejected by the network.

### PR DESCRIPTION
**Pull request by Sventimir**
This PR fixes two bugs, which caused balance reconciliation failures in `rosetta-cli` tests:
* `/account/balance` when asked for a balance at a block before any transaction involving the queried account was performed, Rosetta reported the most recent balance;
* `/block` only reported internal operations when there had been an account creation fee associated with it.

In order to fix the first bug, `genesis_balance` for each account can now be obtained from GraphQL. `genesis_balance` describes the initial shape of an account it it was present in the genesis ledger or is `null` otherwise.

Manually testing changes:
Set up Rosetta server (this is the easiest to do in sandbox mode), generate some transactions and run `rosetta-cli check:data` against the blockchain. Instructions on how to do it can be found [here](https://github.com/MinaProtocol/mina/blob/develop/src/app/rosetta/rosetta-cli-config/README.md).

Checklist:

- [x] Does this close issues? List them

* Closes #12299

### CODE REVIEW

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

File: src/app/rosetta/lib/block.ml [hunk 1]
```diff
@@ -491,7 +491,7 @@ WITH RECURSIVE chain AS (
         FROM internal_commands i
         INNER JOIN blocks_internal_commands bic ON bic.internal_command_id = i.id
         INNER JOIN account_identifiers ai on ai.id = i.receiver_id
-        INNER JOIN accounts_created ac on ac.account_identifier_id = ai.id
+        LEFT JOIN accounts_created ac on ac.account_identifier_id = ai.id
```
Comment (joaosreis) [inline src/app/rosetta/lib/block.ml:494]: I think there should be no problem with the join becoming a `LEFT JOIN` since the only field from `accounts_created` we need is `creation_fee` and the OCaml type for it it was already `option int64`.

**Review by joaosreis — APPROVED** [review]
LGTM!

File: src/app/rosetta/lib/account.ml [hunk 2]
```diff
@@ -113,158 +117,153 @@ module Sql = struct
...
-              ~start_slot:
+       let%bind timing_info_opt =
+         Archive_lib.Processor.Timing_info.find_by_account_identifier_id_opt
+           (module Conn)
+           account_identifier_id
+         |> Errors.Lift.sql ~context:"Finding timing info"
+       in
+       let end_slot =
+         UInt32.of_int
+           (Int.of_int64_exn requested_block_global_slot_since_genesis)
```
Comment (ylecornec) [inline src/app/rosetta/lib/account.ml:171]: This is existing code but I think the following should be better. It is simpler and can avoid unneeded exceptions on 32 bits systems.

```suggestion
         UInt32.of_int64 requested_block_global_slot_since_genesis
```

**Review by ylecornec — APPROVED** [review]
I have two comments but it looks good to me as well.

File: src/app/rosetta/lib/block.ml (hunk 1 above)
Comment (Sventimir) [reply src/app/rosetta/lib/block.ml:494]: Yes, that was my reasoning as well.

**Review by joaosreis — APPROVED** [review]

**Review by joaosreis — APPROVED** [review]

**Comment by Sventimir** [comment]
!ci-build-me

**Review by lk86 — APPROVED** [review]

**Comment by Sventimir** [comment]
!ci-build-me

**Review by bkase — APPROVED** [review]
This looks like it may work, but just to warn you:

We did a lot of work to ensure that Rosetta endpoints that the CLI tool hammered often did not need to query GraphQL. We found that Rosetta operators had trouble reconciling the chain quickly enough when GraphQL was a dependency (it's a lot faster to just hammer postgres)

It would be safer to load the genesis ledger into the Rosetta process at compile time and pull the values directly from memory rather than depending on a node query.

However, maybe Mina's daemon is stable enough these days that you won't run into this issue anymore and depending on GraphQL may just work.

**Comment by Sventimir** [comment]
I considered loading the genesis ledger to Postgres, but then again I thought why bother, if the data can be readily available from GraphQL. I was not aware of these performance concerns. I can do some performance testing, if it'll make you sleep easier. Alternatively I could try to redesign this so that GraphQL is only hit when it's necessary. I doubt this path will be taken frequently in practice, so it probably makes sense to do this anyway.

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by bkase** [comment]
putting the genesis data into postgres probably makes a lot of sense

**Comment by psteckler** [comment]
> putting the genesis data into postgres probably makes a lot of sense

`Archive.Lib.Processor.add_genesis_accounts`, called by `setup_server`, is meant to do that already.

**Comment by Sventimir** [comment]
@psteckler, that's good to know. Genesis balances definitely are not put in Postgres. I'm going to investigate why.

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
@bkase, @lk86, please have a look again, esp. at the `fixup!` comment.

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Review by joaosreis — APPROVED** [review]
