### PR TITLE
nest chain locations develop v2

### LINKED ISSUE #17763: Add a chain name to the daemon config
Related to https://github.com/MinaProtocol/mina/issues/17762.

The hard fork automation MIP proposes that the mesa chain state be stored in `chain-state/mesa-{network_id}` in the mina config directory. More generally, we'd like to use the scheme `chain-state/{chain_name}-{network_id}` in future for our chain state management.

The `network_id` already exists as a parameter of the `daemon` config (compiled config and runtime config, though we want to remove it from the compiled config). The `chain_name` does not, so to support this chain state management scheme we should add something like a `chain_name` to the config, somewhere. Likely just the runtime config.

There would be an associated enum of chain names and a parser/renderer for this type as well, I'd imagine. This would include the names of chains we know the daemon can operate with. It could also include names of chains we know we aren't compatible with, if we wanted to fail to start up with a nice error message if given an incompatible chain name. As an aside, this could theoretically be a type with multiple variants (aside from, potentially, an `Other_chain of string`) because multiple future hard forks might be compatible with the same daemon executable.

The current default chain name would presumably be rendered as `"berkeley"`, and the next chain name (used in the automatic hard fork config and the post hard fork daemon version) would be `"mesa"`.

### PR DESCRIPTION
**Pull request by martyall**
fixes #17763 , replaces #18324

## Problem statement
As part of the hard-fork automation, we want to partition the "workspace" directories for the node for the before/after upgrade times. In order to do this, we settled on e.g.

```
~/.mina-config/<chain_id>/genesis/{ledger_files}
```

Again, the problem is that because of the way that `chain_id` was computed, it required unpacking the ledger to retrieve the `total_currency` (technically it would also compute the ledger hash from the unpacked ledger). Everything other contributing argument could be given without touching the ledger. 

Using the `total_currency` in the `chain_id` computation was redundant from a uniqueness point of view because it was already hashing the ledger.

## Solution
After landing  
- #18269 
- #18298

We can now "short circuit" unpacking for production environments by
- use `0` for the total currency
- use the supplied ledge hash declared in the config json

This means we can compute _a_  suitable `chain_id` (though now computed differently) without unpacking the ledger, and we can do the desired directory nesting. 

Because the daemon already does an assert/compare between the declared hash and computed hash after unpacking the ledger, this is sound. For environments that don't declare the ledger hashes in the json config (like maybe certain testing/local envs), we don't bother with the directory nesting. 

## "breaking changes"
- Genesis_proof / Precomputed_values inputs used to take an `constraint_system_digests Lazy.t Option.t`, but I didn't see any useful reason to keep the Option if the computation itself is lazy. It was useful in the impl to remove this.
- There was an RPC endpoint to get the `chain_id` endpoints which would have been annoying to continue to support, and there is no indication that we still need it. It was removed

### CODE REVIEW

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

File: src/lib/genesis_ledger_helper/genesis_ledger_helper.ml [hunk 1]
```diff
@@ -701,23 +701,28 @@ module Genesis_proof = struct
...
+        ~constraint_constants:light_proof.constraint_constants
+    in
     { Genesis_proof.Inputs.runtime_config
     ; constraint_constants = light_proof.constraint_constants
     ; proof_level = light_proof.proof_level
     ; genesis_ledger = ledger
     ; genesis_epoch_data
     ; consensus_constants = light_proof.consensus_constants
     ; protocol_state_with_hashes
-    ; constraint_system_digests = None
```
Comment (martyall) [inline src/lib/genesis_ledger_helper/genesis_ledger_helper.ml:720]: @cjjdespres This is what I wanted to flag.

File: buildkite/src/Jobs/Test/ChainIdTestDevnet.dhall [hunk 2]
```diff
@@ -17,6 +17,6 @@ let deps =
         Dockers.DepsSpec::{ network = network, profile = Profile.Type.Devnet }
 
 let expectedChainId =
-      "29936104443aaf264a7f0192ac64b1c7173198c1ed404c1bcff5e562e05eb7f6"
+      "8c6312664c60ecc4c0c695e69f6301692c0b20f354b55e08e69a289f3d373e50"
```
Comment (martyall) [inline buildkite/src/Jobs/Test/ChainIdTestDevnet.dhall:20]: This is wrong, but this has been disabled on develop. Once we have the `endomul` stuff I will go back and change these

File: buildkite/src/Jobs/Test/ChainIdTestMainnet.dhall [hunk 3]
```diff
@@ -17,7 +17,7 @@ let deps =
         Dockers.DepsSpec::{ network = network, profile = Profile.Type.Mainnet }
 
 let expectedChainId =
-      "a7351abc7ddf2ea92d1b38cc8e636c271c1dfd2c081c637f62ebc2af34eb7cc1"
```
Comment (martyall) [inline buildkite/src/Jobs/Test/ChainIdTestMainnet.dhall:20]: This is wrong, but this has been disabled on develop. Once we have the `endomul` stuff I will go back and change these

**Comment by martyall** [comment]
!ci-build-me

**Comment by cjjdespres** [comment]
Funny, the `connect-to-testnet` is now correctly failing because the chain ID computation changed. I think we'll still want to add the missing digests, of course.

File: src/app/cli/src/init/chain_state_locations.ml [hunk 4]
```diff
@@ -17,20 +17,123 @@ type t =
...
+           :
+           Genesis_data.Hashed.t Genesis_data.Epoch.tt
+         ->
+        { staking =
+            { ledger =
+                { Genesis_data.Hashed.hash =
+                    Mina_base.Frozen_ledger_hash.of_base58_check_exn staking
+                ; total_currency = Currency.Amount.zero
+                }
+                (* TODO: check if this of_string is right *)
```
Comment (cjjdespres) [inline src/app/cli/src/init/chain_state_locations.ml]: I think this TODO and the other one below can be removed

File: src/lib/chain_id/chain_id.ml [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+    { genesis_state_hash : Data_hash_lib.State_hash.t
+    ; genesis_constants : Genesis_constants.t
+    ; constraint_system_digests : (string * Md5_lib.t) list Lazy.t
+    ; protocol_transaction_version : int
+    ; protocol_network_version : int
+    }
+end
+
+let of_inputs (inputs : Inputs.t) =
+  (* if this changes, also change Mina_commands.chain_id_inputs *)
```
Comment (cjjdespres) [inline src/lib/chain_id/chain_id.ml]: This comment no longer applies, I think

File: src/lib/genesis_ledger_helper/genesis_ledger_helper.ml (hunk 1 above)
Comment (cjjdespres) [reply src/lib/genesis_ledger_helper/genesis_ledger_helper.ml:720]: Right. Well, judging from the diff I don't think anything was relying on the possibility of `None` except for the code that filled in the constraint system digests later on. Seems fine.

**Review by cjjdespres — APPROVED** [review]
All right. I think the connect to mainnet/devnet tests will still need to be updated, but that's going to be revealed in the CI run for this PR anyway.

The new change is adding the zkapp digests to the constraint system digests, which we discussed internally - it seems to be an oversight from the previous hard fork that they weren't included in the list of digests. Not including them means that the chain ID does not change when the zkapp circuits change, which is undesirable. Without this change, two daemons with incompatible proof systems could have the same rendezvous string for p2p communication, so they'd end up talking to each other and trying to establish consensus. This isn't fatal, because they wouldn't be able to verify each other's proofs, but it does lead to a lot of wasted communication.

**Comment by cjjdespres** [comment]
As a historical note: the zkapp digests were added in a different PR here: https://github.com/MinaProtocol/mina/commit/0abbb467ba05d373cf9a59c8561361951e8de02a but had to be removed in a later commit to satisfy chain ID compatibility. Since we're hard forking, we can include that change now. The commit 90dc338054527f8d063d1576d3073a9f8fca4a94 that will be merged into develop now is a copy of part of that older effort.

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-nightly-me

**Comment by martyall** [comment]
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/4216

**Comment by cjjdespres** [comment]
I think you need to run the linter on the dhall files.

A `single-node-tests` test did fail:

```
{"timestamp":"2026-03-12 05:03:13.682003Z","level":"Spam","message":"Running command (from .): $command","metadata":{"command":"/usr/local/bin/mina daemon --seed --demo-mode --insecure-rest-server --working-dir . --client-port 8031 --rest-port 3085 --config-directory /tmp/mina_automation.tmp.fdd8af/mina_spun_test.tmp.0ac59a --genesis-ledger-dir /tmp/mina_automation.tmp.fdd8af/mina_genesis_state.tmp.c81cdc --external-ip 0.0.0.0 --libp2p-keypair /tmp/mina_automation.tmp.fdd8af/mina_test_libp2p_keypair.tmp.84891a/privkey --peer-list-url http://bootnodes.minaprotocol.com/networks/devnet.txt","envs":[]}}
ASSERT Expected warning about HTTP being insecure in daemon logs
[ERROR]             peer-list-url-http-warning                  0   The mina daemon warns when --peer-list-url uses http:// instead of https://.
-- peer-list-url-http-warning.000 [The mina daemon warns when --peer-list-url uses http:// instead of https://.] Failed --
```

But that's unrelated - I ran it locally and it just barely succeeds with its 5 second test time. I'm assuming it failed because it took slightly longer for the daemon to start in the CI. That time will need to be increased separately.

**Comment by martyall** [comment]
!ci-build-me

**Comment by martyall** [comment]
!ci-build-me

File: buildkite/src/Command/Base.dhall [hunk 6]
```diff
@@ -245,7 +245,7 @@ let build
               }
           , soft_fail = c.soft_fail
           , skip = c.skip
-          , `if` = c.if_
+          , if = c.if_
```
Comment (dkijania) [inline buildkite/src/Command/Base.dhall:248]: Which dhall version are you using ? I guess this should be not changed

Comment (martyall) [reply buildkite/src/Command/Base.dhall:248]: it was via nix, apparently they produced different things but they both pass the `check` tests

Comment (cjjdespres) [reply buildkite/src/Command/Base.dhall:248]: Weird. I tested the nix-installed dhall locally and it didn't do that for me. Oh, I probably only tested on `compatible`. Maybe there would have been a minor change on `develop` if I had tested it. I remember seeing that there was some backtick replacement in the reformatting target in the makefile, so I wonder if that has something to do with it.

Anyway, if it works then it's fine.

**Comment by martyall** [comment]
!ci-build-me
