### PR TITLE
Fix local state loading in epoch one

### LINKED ISSUE #18676: Mina Node Stuck in Bootstrap - Epoch Ledger Sync Fails After Num_accounts Query
## Summary

A Mina plain node gets stuck indefinitely in bootstrap mode during epoch ledger synchronization. The node successfully initiates epoch ledger sync and receives `Num_accounts` responses from all peers, but never progresses to request additional ledger data needed to complete the synchronization. This has been confirmed to be a distinct failure mode from #18380.

## Environment

- **Node Type**: Mina plain node (itn-standard-plain-1)
- **Peer ID**: `12D3KooWQoNikmozrvEbE9me3PfpoJ4VzmP1tz3ZeUazYPfRDnX7`
- **Network**: ITN testnet
- **Log Timestamp**: 2026-03-25 07:24:00 – 09:30:00 UTC

## Background / Incident Context

This issue was discovered during an ITN testnet incident on 2026-03-25. Several nodes (coordinator, plain-1, plain-3, plain-4, seed-1) were restarted by automated uptime management after running for over a week. Following restart, these nodes entered bootstrap and failed to recover, leaving the network SNARK-work starved.

The coordinator restarted at 19:26 UTC on 2026-03-24 and entered a restart loop, unable to synchronize. Other nodes followed the same pattern. At the time of investigation, 5 of 10 nodes were in sync and 5 were stuck in bootstrap — including nodes that were connected to healthy peers, ruling out peer unavailability as the cause.

## Distinction from #18380

Issue #18380 describes a bootstrap failure where `download_best_tip` returns `None` due to zero peer responses, causing an early deadlock before epoch ledger sync begins.

This failure diverges from that path:

- The node **successfully retrieves best tips** from peers (multiple responses   between 07:25:15–07:25:22)
- The node **loads the frontier from disk** successfully at 07:26:16 
- The node **enters epoch ledger sync** normally
- Epoch ledger sync **receives valid `Num_accounts` responses** from all peers
- Sync then **stalls mid-way** — not at startup

The failure mode here is a mid-sync stall within the epoch ledger sync subsystem, entered via a working best tip and a disk-loaded frontier. The fix
for #18380 will not cover this case.

### What Works

- ✅ Best tip download from peers (valid responses received)
- ✅ Frontier loaded from disk
- ✅ Epoch ledger sync initiated
- ✅ `Num_accounts` queries issued and answered by all 10 peers
- ✅ RPC connectivity confirmed (node visible in peer transaction gossip and rate
  limiting logs)

### What Fails

- ❌ No `What_child_hashes` queries ever generated
- ❌ No `What_contents` queries ever generated
- ❌ No multi-item batch requests (`"n"` is always `1`)
- ❌ No `handle_answer` or `handle_node` trace logs
- ❌ Node loops on `Num_accounts` queries (~30 total across ~3 rounds) and never
  exits bootstrap

### Confirmed via grep

All 30 downloader results in the log are `Num_accounts` — no other query type appears:

```bash
$ grep '"result is $result' /tmp/itn-standard-plain-1-5fc4f48b85-ckvqn.prev.log \
    | jq '.metadata.result.elts[0][1][0]' | sort | uniq -c
     30 "Num_accounts"
```

No follow-up queries generated:

```bash
$ grep -E "What_child_hashes|What_contents" \
    /tmp/logs-2026-mar25/itn-standard-plain-1-5fc4f48b85-ckvqn.prev.log
# (no output)
```

No batch requests (n ≥ 2) present:

```bash
$ grep -E "downloading.*from.*peer.*n.*[2-9]" \
    /tmp/logs-2026-mar25/itn-standard-plain-1-5fc4f48b85-ckvqn.prev.log \
    | grep -v "Num_accounts" | wc -l
0
```

### Sample log entries

Successful `Num_accounts` query (pattern repeated ~30 times):

```
"Downloader: downloading $n from $peer"
"result is {"length":1,"elts":[["jwHCUmPYgfGRR8h9y73uvA6n4bcCZ7zBatKWmpkkrSqbfTcinHZ",
  ["Num_accounts"]]]}"
```

## Expected Behavior

1. ✅ `Num_accounts` query → valid response received
2. ❌ `handle_num_accounts` → should call `handle_node` *(not happening)*
3. ❌ `handle_node` → should enqueue `What_child_hashes` / `What_contents`
   *(not happening)*
4. ❌ Follow-up queries → responses → sync complete *(not happening)*

## Files to Investigate

- `src/lib/syncable_ledger/syncable_ledger.ml` — `handle_num_accounts`
- `src/lib/syncable_ledger/syncable_ledger.ml` — `handle_node`
- `src/lib/syncable_ledger/syncable_ledger.ml` — `main_loop` query generation
- Bootstrap / frontier loading code — specifically the path where a frontier is
  restored from disk before epoch ledger sync begins

## Logs

- Full `.mina-config` directories of nodes: `gs://tmp-hardfork-testing/logs-2026mar25-bootstrap-failure`
- Recent log dumps: https://drive.google.com/drive/folders/1vbsL6QCqVWRHSz1V2m2EcLSTJ0k_DoH_

## Impact

- Nodes that have been running for over a week cannot successfully restart and rejoin the network
- Affected nodes cannot participate in consensus or serve epoch ledger data
- SNARK works stop being produced if all coordinators get affected
- Issue is reliably triggered by automated uptime restarts after long-running sessions, making it a recurring operational hazard

## Severity

**High** — Nodes cannot bootstrap after restart, with confirmed network-level impact on SNARK work availability. Likely to recur on any node restart after extended uptime.

### PR DESCRIPTION
**Pull request by georgeee**
# Problem

When a Mina node restarts after having witnessed at least one epoch transition, it could incorrectly load the genesis staking epoch ledger instead of the genesis *next* epoch ledger in the staking position. This caused the node to enter a broken sync state where it attempts to download the genesis next epoch ledger from peers — but peers reject such requests, since ledger sync endpoints ignore requests for genesis ledgers. The node then stalls indefinitely in bootstrap.

The root cause is in `proof_of_stake.ml`'s local state loading logic. After one epoch transition:

- The staking epoch ledger should be the **genesis next epoch ledger**
- The next epoch ledger should be some **new non-genesis ledger** (present on disk)

However, when the staking epoch ledger database is absent on disk (because we only write non-genesis ledgers to disk), the code was unconditionally falling back to `genesis_epoch_ledger_staking` — even when the correct fallback should have been `genesis_epoch_ledger_next`.

# Fix

Load the next epoch ledger first, and use whether it was loaded from genesis or from disk to determine the correct fallback for the staking epoch ledger:

- If next epoch ledger loaded from **genesis** → no epoch transition has occurred → staking fallback is `genesis_epoch_ledger_staking` (previous behavior, correct for epoch 0)
- If next epoch ledger loaded from **disk** → at least one epoch transition has occurred → staking fallback should be `genesis_epoch_ledger_next`

This relies on the invariant that only non-genesis ledgers are written to disk, which is documented in the code comment.

# Root cause analysis

This failure mode was initially investigated as a variant of #18380 (bootstrap stall due to failed best tip download), but is distinct: the node successfully downloads a best tip, loads its frontier from disk, and enters epoch ledger sync normally. Sync receives valid `Num_accounts` responses from peers but never progresses to `What_child_hashes` or `What_contents` — because the ledger hash being synced is the genesis next epoch ledger hash, and peers silently drop sync requests for genesis ledgers.

The incorrect staking ledger loaded on restart is the source of the mismatch that triggers the failed sync.

# Checklist

Explain how you tested your changes:
* [ ] TODO Not tested yet

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them

* Closes #18676

### CODE REVIEW

**Comment by georgeee** [comment]
!ci-build-me

**Comment by amc-ie** [comment]
!ci-bypass-changelog

File: src/lib/consensus/proof_of_stake.ml [hunk 1]
```diff
@@ -531,19 +531,38 @@ module Make_str (A : Wire_types.Concrete) = struct
...
         let staking_epoch_ledger_config =
           ledger_config epoch_ledger_uuids.staking
         in
         let staking_epoch_ledger =
+          (* If next epoch ledger is loaded from disk, then we know that
+           * at least one epoch transition has happened, hence either the staking
+           * ledger will also be loaded from disk or the genesis next ledger must
+           * be the used.
+           *
+           * This code heavily relies on the fact that we writer only non-genesis
```
Comment (glyh) [inline src/lib/consensus/proof_of_stake.ml:556]: typo: writer -> write.

**Comment by glyh** [comment]
I understand what the code is doing here. However, if an user accidentally deleted non-genesis current(staking) epoch ledger with non-genesis next epoch ledger present on disk, what will happen? 

EDIT: my bad, it seems the node would just delete everything and retry syncing. 

I guess, in a more general sense, it's a bad idea to rely on on-disk presence to decide had we transitioned to any epoch or not. But probably that's the best we can do here without breaking change?

Maybe, a proper solution(requiring HF) should be fixing this instead?

> This caused the node to enter a broken sync state where it attempts to download the genesis next epoch ledger from peers — but peers reject such requests, since ledger sync endpoints ignore requests for genesis ledgers

Maybe peer should just point out to a node its local consensus state is broken and how it's broken?

**Comment by glyh** [comment]
I guess, approving still so we can release faster.

**Review by glyh — APPROVED** [review]

**Comment by glyh** [comment]
Reading the code closely, I'm suprised we don't store which epoch we're in anywhere in on-disk state and not nearby the structure Local_state.

A real, clean solution should be having a table that we can query the current ledger by epoch, so there's no need all the logic fiddling current/next ledgers ever.
