### PR TITLE
mina-local-network: fix nonce in inherit mode

### LINKED ISSUE #18466: [mina-local-network] infer nonce correctly when restarting a network
In this script, we're always using nonce 0 when starting the network, which is not guaranteed to be always correct, especially when restarting a network.

We should put in some effort to use the correct nonce when sending txns.

### PR DESCRIPTION
**Pull request by glyh**
Skip the initial nonce-0 setup transactions when restarting with inherit mode, and query inferredNonce from the node via GraphQL instead of hardcoding fee_payer_nonce=1/sender_nonce=1.

closes https://github.com/MinaProtocol/mina/issues/18466

### CODE REVIEW

File: scripts/mina-local-network/mina-local-network.sh [hunk 1]
```diff
@@ -1290,12 +1290,22 @@ if ${VALUE_TRANSFERS} || ${ZKAPP_TRANSACTIONS}; then
...
+      ${MINA_EXE} client send-payment -rest-server ${REST_SERVER} -amount 1 -nonce 0 -receiver "${PUB_KEY}" -sender "${PUB_KEY}"
+    fi
   fi
 
-  fee_payer_nonce=1
-  sender_nonce=1
+  FEE_PAYER_PUB_KEY=$(cat "${FEE_PAYER_KEY_FILE}.pub")
+  SENDER_PUB_KEY=$(cat "${SENDER_KEY_FILE}.pub")
+
+  fee_payer_nonce=$(curl -sS -g -X POST -H "Content-Type: application/json" \
```
Comment (dkijania) [inline scripts/mina-local-network/mina-local-network.sh:1303]: Another potential candidate to be replaced by future mina-graphql cli

**Review by dkijania — APPROVED** [review]

File: scripts/mina-local-network/mina-local-network.sh (hunk 1 above)
Comment (glyh) [reply scripts/mina-local-network/mina-local-network.sh:1303]: Agreed, plenty of these in our codebase.

**Comment by glyh** [comment]
!ci-build-me

**Comment by glyh** [comment]
Rebased on to compatible to fix CI jobs.

**Comment by glyh** [comment]
!ci-build-me

**Comment by amc-ie** [comment]
!ci-bypass-changelog
