### PR TITLE
Transaction pool parties async bug fix

### LINKED ISSUE #11393: Transaction pool async bug (diff application)
The bug is caused by the fact that the `verify` function precomputes updates to the pool asynchronously, and those updates are blindly copied into the data structure in the `apply` function. There is a mutex locked between these function calls that prevents race conditions within `verify`+`apply` cycles, but handling transition frontier diffs can happen asynchronously outside of this cycle, causing changes to the underlying pool data structure between calls to `verify` and `apply`.

### PR DESCRIPTION
**Pull request by nholland94**
Closes #11393.

To fix this bug, I removed the asynchronous computation of indexed pool updates from the `verify` entirely. Instead, that logic is moved into `apply`, where all of the commands in a transaction pool diff are applied to the pool within a single scheduler cycle, preventing race conditions with `handle_transition_frontier_diff`. The `verify` function still runs asynchronously, but it is now only responsible for validating transactions in isolation to the pool state (validating proofs, signatures, and global restrictions such as minimum fee).

### CODE REVIEW

File: src/lib/network_pool/transaction_pool.ml [hunk 1]
```diff
@@ -1367,135 +1063,172 @@ struct
...
-                    "dropped commands due to transaction replacement: $dropped"
-                    ~metadata:[ ("dropped", Cs.to_yojson dropped) ] ;
-                check_dropped (Sequence.of_list dropped) ;
-                go txs )
+        (* determine if we should re-broadcast this diff *)
+        let decision =
+          if
+            List.exists rejected ~f:(fun (_, error) ->
+                Diff_error.grounds_for_diff_rejection error )
+          then `Reject
```
Comment (deepthiskumar) [inline src/lib/network_pool/transaction_pool.ml:1204]: Why do we accept some transactions from the diff that is not broadcast-able?

Comment (deepthiskumar) [reply src/lib/network_pool/transaction_pool.ml:1209]: Could this cause mem pool inconsistencies?

Comment (nholland94) [reply src/lib/network_pool/transaction_pool.ml:1223]: It could contribute to it in theory, but I don't think it would be a major contributor. This basically only happens if the txn pool diff contains a malicious transaction (eg: invalid signature). We would only accept still-valid txns from the diff, but would refuse to send the diff to another peer since it contained some malicious data.

I'm not sure this behavior is the best, but I'm also not certain if it's important to update now. I think the issue it causes is very small and it's unlikely we will see it in practice, so I'm inclined to just wait for a future txn pool rewrite for this edge case.

File: src/lib/network_pool/transaction_pool.ml [hunk 2]
```diff
@@ -968,385 +935,114 @@ struct
...
+            Lru_cache.add t.recently_seen (Lru_cache.T.hash diff.data)
+          in
+          ok_if_true (not already_mem) ~error:"Recently seen"
         in
-        let h = Lru_cache.T.hash diffs.data in
-        let (`Already_mem already_mem) = Lru_cache.add t.recently_seen h in
-        if (not allow_failures_for_tests) && already_mem && not is_sender_local
-        then
-          (* We only reject here if the command was from the network: the user
-             may want to re-issue a transaction if it is no longer being
```
[the remark this answers is not in the document]
Comment (nholland94) [reply src/lib/network_pool/transaction_pool.ml:1100]: I updated the predicate in my new code to be the same.

[the remark this answers is not in the document]
Comment (nholland94) [reply src/lib/network_pool/transaction_pool.ml:1100]: I actually have a TODO in the code to just remove this LRU completely as I'm pretty certain we never hit this code (libp2p already has a cache for gossip messages, and its more powerful than this one). I'm just leaving this intact for now just in case it does get hit under rare scenarios.

File: src/lib/network_pool/transaction_pool.ml [hunk 3]
```diff
@@ -981,400 +948,125 @@ struct
...
+                     ~f:
+                       (User_command.to_verifiable ~ledger ~get:Base_ledger.get
+                          ~location_of_account:Base_ledger.location_of_account ) ) )
+        in
+        match%bind.Deferred
+          O1trace.thread "batching_transaction_verification" (fun () ->
+              Batcher.verify t.batcher diff' )
+        with
+        | Error e ->
+            [%log' error t.logger] "Transaction verification error: $error"
```
Comment (deepthiskumar) [inline src/lib/network_pool/transaction_pool.ml:1039]: should we include the diff here? (maybe in a debug log)

File: src/lib/network_pool/transaction_pool.ml [hunk 4]
```diff
@@ -981,400 +948,125 @@ struct
...
+            let msg = Verifier.invalid_to_string invalid in
+            [%log' error t.logger]
+              "Batch verification failed when adding from gossip"
+              ~metadata:[ ("error", `String msg) ] ;
+            let%map.Deferred () =
+              Trust_system.record_envelope_sender t.config.trust_system t.logger
+                (Envelope.Incoming.sender diff)
+                ( Trust_system.Actions.Sent_useless_gossip
+                , Some
+                    ( "rejecting command because had invalid signature or was \
```
Comment (deepthiskumar) [inline src/lib/network_pool/transaction_pool.ml:1052]: invalid signature or proof

File: src/lib/network_pool/transaction_pool.ml [hunk 5]
```diff
@@ -1395,135 +1087,175 @@ struct
...
         let pool, dropped_for_size =
-          drop_until_below_max_size pool ~pool_max_size
+          drop_until_below_max_size pool ~pool_max_size:t.config.pool_max_size
+        in
+        (* handle drops of locally generated commands *)
+        let all_dropped_cmds =
+          Sequence.to_list (Sequence.append dropped_for_add dropped_for_size)
+        in
+        let all_dropped_cmd_hashes =
+          List.map all_dropped_cmds
```
Comment (deepthiskumar) [inline src/lib/network_pool/transaction_pool.ml:1179]: Maybe a debug log here to show how many transactions were dropped?

**Review by deepthiskumar — APPROVED** [review]
Looks great!
Just some minor comments
