### PR TITLE
[transaction_logic] Fix sign check bug in currency amount.

### LINKED ISSUE #12604: [bug] Transaction logic: 0 amount of currency is considered positive.
In `Mina_transaction_logic` there's an extension of `Currency.Amount.Signed` module, which introduces its own functions for checking whether a value is positive or negative. `0` is considered positive by those functions. Write unit tests for the module.

### PR DESCRIPTION
**Pull request by Sventimir**
In `Mina_transaction_logic` there's an extension of `Currency.Amount.Signed` which defines functions `is_pos` and `is_neg`. For 0 `is_pos` erroneously returns `true`. Moreover, the same functionality is already implemented correctly in the base currency library, so it should be imported from there. In the future we should probably remove these synonyms in favour of original function names.

Explain your changes:
* Refactor `Amount` out of `Mina_transaction_logic.Make` functor so that it can be tested.
* Replaced the definition with functions already defined in `Currency.Amount.Signed`.

Explain how you tested your changes:
* Wrote unit tests which fail before this change and pass afterwards.

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Does this close issues? List them

* Closes #12604

### CODE REVIEW

**Comment by Sventimir** [comment]
!ci-build-me

**Review by ejMina226 — APPROVED** [review]

**Review by mrmr1993 — CHANGES_REQUESTED** [review]
This behaviour is intended to be consistent with in-circuit version. To reduce cost of the in-circuit version, the sign is a boolean rather than a tri-state variable that we'd need here.

If the name perturbs you, you should probably change that instead.

Also, please do not refactor code out of the transaction logic while we're actively working on it.

**Comment by Sventimir** [comment]
@mrmr1993, as I have renamed these functions, I realised that its usage was probably also bad. I suspect we really need to have `is_negative` rather than `is_non_positive` in there. What do you think?

File: src/lib/transaction_logic/mina_transaction_logic.ml [hunk 1]
```diff
@@ -1612,9 +1612,9 @@ module Make (L : Ledger_intf.S) :
 
         let if_ = value_if
 
-        let is_pos (t : t) = Sgn.equal t.sgn Pos
+        let is_non_negative (t : t) = Sgn.equal t.sgn Pos
 
-        let is_neg (t : t) = Sgn.equal t.sgn Neg
+        let is_non_positive (t : t) = Sgn.equal t.sgn Neg
```
Comment (mrmr1993) [inline src/lib/transaction_logic/mina_transaction_logic.ml:1617]: This renaming is wrong, revert

**Review by mrmr1993 — CHANGES_REQUESTED** [review]

File: src/lib/transaction_logic/mina_transaction_logic.ml (hunk 1 above)
Comment (Sventimir) [reply src/lib/transaction_logic/mina_transaction_logic.ml:1617]: It returns `true` for `{ magnitude : 0; sgn : Neg }`, which behaves like a proper `0`

Comment (Sventimir) [reply src/lib/transaction_logic/mina_transaction_logic.ml]: Reverted. It would have been very helpful to know in advance the invariant that `{magnitude = zero; sgn = Neg}` is never expected to be produced (as both these functions break down on this value. Sadly, the type's internal structure is exposed, so it's still possible to create such a value by hand, so technically it's not guaranteed to hold. I added a comment to explain this.

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Review by mrmr1993 — APPROVED** [review]

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me

**Comment by Sventimir** [comment]
!ci-build-me
